symbols:
  - VNM
  - GVR
  - GMD
  - PLX


start_date: "2024-01-01"
end_date: "2026-01-14"
resolution: "1D"

data_paths:
  raw: "data/raw/ohlcv"
  processed: "data/processed"

logging:
  level: "INFO"
  dir: "logs"

retry: 3
